# Generated by Django 3.2.6 on 2021-08-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210724_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
